apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: pv-models-cache
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    path: /mnt/vllm
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: manual
  volumeMode: Filesystem

