---
apiVersion: v1
kind: Service
metadata:
  name: lightspeed-api
  namespace: openshift-lightspeed
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app.kubernetes.io/name: lightspeed-service-api
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
  namespace: openshift-lightspeed
spec:
  port:
    targetPort: https
  to:
    kind: Service
    name: lightspeed-api
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None